# Generated by Django 6.0.2 on 2026-02-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(default='School Campus', max_length=200)),
                ('description', models.TextField()),
                ('is_holiday', models.BooleanField(default=False)),
            ],
        ),
    ]
