# Generated by Django 6.0.2 on 2026-02-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Exam', 'Examination'), ('Holiday', 'Holiday'), ('Event', 'Event')], default='General', max_length=20)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_urgent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
