# Generated by Django 6.0 on 2026-03-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_or_era', models.CharField(help_text="e.g., '1988' or 'The Early Years'", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'History Entries',
                'ordering': ['year_or_era'],
            },
        ),
    ]
