# Generated by Django 6.0.2 on 2026-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_achievementcategory_achievementitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementcategory',
            options={'verbose_name_plural': 'Achievement Categories'},
        ),
        migrations.RenameField(
            model_name='achievementcategory',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='achievementcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='achievementitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
