# Generated by Django 6.0 on 2026-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_achievementcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_en', models.CharField(max_length=200)),
                ('student_name_np', models.CharField(blank=True, max_length=200)),
                ('dob_ad', models.DateField()),
                ('dob_bs', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=200)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('last_school_attended', models.CharField(max_length=200)),
                ('grade_applying_for', models.CharField(max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
