# Generated by Django 6.0.2 on 2026-02-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('hod_name', models.CharField(max_length=100, verbose_name='Head of Department')),
                ('contact_email', models.EmailField(max_length=254)),
                ('cover_image', models.ImageField(upload_to='departments/')),
            ],
        ),
    ]
